### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by jpoa** [zatosource/ide-pycharm#2]
Greetings,

The extension is accessing `/zato/ide-deploy` but from what I saw on Zato3 the URL is `/ide-deploy`, when issuing a request via curl I get:

> CID:`e1346bca1e7b544a7725c354` Unknown URL:`/zato/ide-deploy` or SOAP action:`

but I get access denied when I try to reach `/ide-deploy` (as expected since I was not sending any auth).

Could it be that the endpoint changed in the new release or am I missing something on the configurations?

Happy to provide a PR if that is the case.

**Comment by dsuch** [comment]
Thanks - a PR would be appreciated, the correct path is /ide-deploy indeed.

**Comment by emre** [comment]
Hello @dsuch,

Did you update the plugin?

I am getting this.

<img width="399" alt="screen shot 2018-08-13 at 4 52 34 pm" src="https://user-images.githubusercontent.com/72460/44036009-723f8ef4-9f19-11e8-9e63-65510eb939d6.png">

**Comment by jpoa** [comment]
@emre if it makes your life easier I have attached the compiled plugin.

I think @dsuch might be on vacation at the moment.

[zato-1.0.1.zip](https://github.com/zatosource/ide-pycharm/files/2283229/zato-1.0.1.zip)

**Comment by emre** [comment]
@jpoa 

Thanks!

**Comment by dsuch** [comment]
Thanks @jpoa and @emre - I will update the plugin in the next week.

**Comment by dsuch** [comment]
Hello @jpoa and @emre - this is just a quick note that I have stumbled upon an issue while trying to upload a version of the plugin with the corrected address and I'm working with JetBrains to get it resolved. I will update the ticket as soon as possible.

**Comment by emre** [comment]
Thanks for the update @dsuch, looking to hear from you soon.

**Comment by dsuch** [comment]
Version 1.0.2 with the fixed URL is now available, thanks for reporting it!

https://plugins.jetbrains.com/plugin/10375-zato-hot-deployment
